version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"  # Mapeia a porta 5000 do contêiner para a porta 5000 da máquina host
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/intranet
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=5000

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password  # Use variáveis de ambiente seguras em produção
      MYSQL_DATABASE: intranet
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
