version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py  # Certifique-se de que o arquivo principal do seu aplicativo seja corretamente referenciado
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/intranet
    depends_on:
      - db
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0"  # Aplica migrações e inicia o servidor

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Emiteli@123
      MYSQL_DATABASE: intranet
    ports:
      - "3307:3306"  # Alterando para 3307
    volumes:
      - db_data:/var/lib/mysql